### ISSUE TITLE
求助，找不到power.log路径

### ISSUE THREAD

**Issue by zmy2017** [yuanninesuns/AutoHS#12]
之前我的炉石的power.log文件在logs文件夹里，现在进入对局后找不到power.log文件了

**Comment by LuminaryQuest** [comment]
同求助，炉石的power.log文件改在了具体时间的文件夹里，如Hearthstone_2023_06_13_22_12_04
请问怎么修改代码

**Comment by LuminaryQuest** [comment]
> 之前我的炉石的power.log文件在logs文件夹里，现在进入对局后找不到power.log文件了

鼓捣了一下把赋值代码改为

```python
# 你的Power.log的路径, 应该在你的炉石安装目录下的`Logs/`文件夹中, 这里放的是我的路径
# ** 一定要修改成自己电脑上的路径 **
import os

folder_path = "D:/Hearthstone/Logs/"
folders = os.listdir(folder_path)
latest_folder = max(folders, key=lambda folder: os.path.getctime(os.path.join(folder_path, folder)))
HEARTHSTONE_POWER_LOG_PATH = os.path.join(folder_path, latest_folder, "Power.log")
```

他炉石好像改为了你登录一次就新建一个Hearthstone_2023_06_13_22_12_04（具体时间）的文件夹

记得把路径改成自己的

**Comment by LuminaryQuest** [comment]
但是不知道为什么运行了一会有bug，它突然不会用牌

**Comment by zmy2017** [comment]
现在你解决这个bug了吗？我最近没有登过炉石和脚本，不过据我之前的感觉，不会用牌是因为脚本没有识别进入对战，它的识别是不是就是看有没有power.log？当然这只是我的猜测。

**Comment by LuminaryQuest** [comment]
> 现在你解决这个bug了吗？我最近没有登过炉石和脚本，不过据我之前的感觉，不会用牌是因为脚本没有识别进入对战，它的识别是不是就是看有没有power.log？当然这只是我的猜测。


没解决，总是挂机一段时间就不动了
不知道为啥读取不了
