### ISSUE TITLE
Open 战网: (5, 'BringWindowToTop', '拒绝访问。')

### ISSUE THREAD

**Issue by lingjiao5696** [yuanninesuns/AutoHS#2]
Open 战网: (5, 'BringWindowToTop', '拒绝访问。')
请问下提示这个怎么办

**Comment by yuanninesuns** [comment]
是不是战网没有开？

**Comment by lingjiao5696** [comment]
![Uploading image.png…]()
感谢回复 上面那个确实是战网没有开启，还想请问下一直提示选择英雄的匹配对手的debug时为什么。 英雄使用的是原始皮肤

**Comment by yuanninesuns** [comment]
贴一下真正的报错提示，方便我定位问题。或者形容的再具体一点

**Comment by lingjiao5696** [comment]
![WechatIMG19](https://user-images.githubusercontent.com/93519063/163936989-7b4fb5a7-a9ee-4e11-b68c-380f42dfc6e3.png)
这是上午上班前截的图

**Comment by yuanninesuns** [comment]
没有选择套牌，这个脚本有点小bug，只能选择第一行第三个套牌（有的时候会失灵）；或者进入对战的时候手动选择套牌，之后就默认是你上次选择的套牌了，这个比较靠谱。

**Comment by lingjiao5696** [comment]
明白了 十分感谢🙏
